### ISSUE TITLE
Encrypted Chitu Files

### ISSUE THREAD

**Issue by SaKiEQ** [rudetrooper/Octoprint-Chituboard#11]
I just migrated from Mariner3D to OctoChitu, to be more in line with my other printers... Unfortunately it seems that the firmware issue of encrypted files is standing my way. 
Mariner3D does work even on the new firmware, is there no way of 'merging' the two, or have Mariner3D contribute the essentials to your plugin ? Or is it really an intellectual property issue of dealing with the never version of those files ?

**Comment by rudetrooper** [comment]
Its basically I don't want to support Chitu's badly implemented encryption or create potential legal problems for the Octoprint project. Chitu systems is somewhat anti open source. I can easily enough reverse engineer the encryption and break it using the work done by the LiberatingMarsCLI. The file analysis part of the plugin is essentially borrowed from Mariner. I just added some code for displaying the image files and getting object dimensions from layer slices images.
