### ISSUE TITLE
WARNThe received line contains at least one null byte character at position 0, this hints at some data corruption going on

### ISSUE THREAD

**Issue by mcdviii** [rudetrooper/Octoprint-Chituboard#18]
**Issue**:

I'm receiving title as an error after attempting to print a file with my Elegoo Mars 2 Pro through the Octoprint dashboard. 

Latest Octopi is installed on a rPi Zero 2 W.
GRND, Rx & Tx are wired correctly.
I can send commands to the printer that move the Z axis.
USB is wired correctly. Data lines run directly from rPi pads to a custom USB plug (unpowered).
I can print uploaded files directly from the printer menu screen, but print status stays on "Operational" & does not change.
The rPi is being powered by a buck converter connected from the Chitu board mains input. I was powering from the 5v & ground header pins I installed. No difference in behavior in either case.

**Console Log**:

https://www.toptal.com/developers/hastebin/egelahiqaf.yaml

**Serial Log**:

https://www.toptal.com/developers/hastebin/uduximekap.yaml

**Expected behavior**:

I was under the impression that I could start a print from the Octoprint dashboard.

**Comment by rudetrooper** [comment]
Can you send provide the sliced file and the firmware version so I can try and replicate the issue? Are you starting the prints by selecting the files within the resin folder in the file menu? Also can you provide me the .octoprint/config.yaml file from your pi, the serial settings might be useful.

**Comment by mcdviii** [comment]
Absolutely,

This was downloaded directly from the /resin directory:

https://www.dropbox.com/s/bdownge4ti8mpm3/MixerV2_0.05mm_3h23m.ctb?dl=0

**~/.octoprint/config.yaml**:

https://www.toptal.com/developers/hastebin/ecodubovab.yaml

Firmware ver EL3D-3.0.2

The behavior does not change even when I select a file to print under the /resin folder, but I tried to favor those files after I found that's the directory I needed to be using.

**Comment by rudetrooper** [comment]
Thanks, I'll look into it and try to replicate the issue.

**Comment by mcdviii** [comment]
Thanks for your time & the update on progress. I took another look at my wiring last night & saw no issues. The Pi is pulling under 500mA and at no point goes over that. I'll look into the buck converter, but I feel like the issue is either a misconfiguration or software bug for the moment.

**Comment by mcdviii** [comment]
I've looked into this more; it may still be a wiring issue. My custom USB harness only includes the two data cables & no reference to ground. I will undo my USB wiring & report back--don't wrack your brain too hard on this until I do.

**Comment by mcdviii** [comment]
I've added Ground to the USB data cable with no change in behavior. Which option should I use to upland files with, the Upload button or Upload to SD? Using Upload under /resin works as expected. Upload to SD throws an error about invalid filetype.

**Comment by rudetrooper** [comment]
Upload to SD doesn't work. becuase I overrided that method when I wrote the plugin. Just use the regular upload button, also I tested the file you sent and it works fine on my Elegoo Mars 2 and personal Octoprint setup.

**Comment by mcdviii** [comment]
Any ideas on what to troubleshoot next? Did I miss any setup steps?

Thanks

On February 22, 2022 5:30:45 PM CST, Vikram Sarkhel ***@***.***> wrote:
>Upload to SD doesn't work. becuase I overrided that method when I wrote the plugin. Just use the regular upload button, also I tested the file you sent and it works fine on my Elegoo Mars 2 and personal Octoprint setup.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rudetrooper/Octoprint-Chituboard/issues/18#issuecomment-1048309916
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mcdviii** [comment]
I've been making due by selecting prints from the screen. It has been working well until now. Now I'm getting failed prints where the machine stalls indefinitely on random layers & appears to be unable to read from the file. Similar issues happened with the included USB stick, but the machine recovered with a short "Memory error" message which disappeared once the machine recoverd. Wondering if it's still a hardware interface issue, my control board, or a problem with the formatting of the SAMBA partition.

I've switched SD cards in the Pi with no improvement. If anyone is aware of a better firmware version I could be using, please advise. Thanks!

**Comment by xmodpt** [comment]
What i would try in your case is unplug the pi fro the usb and power. try printing with a normal USB Pen drive if no issues, 2th step would be change the usb cable from pi's data port to front of printer for a new one with the pads correctli taped as per reference.

CrAzY RaBbIt

**Comment by mcdviii** [comment]
I'm confident of the printer end of the data cable being configured correctly. I'm looking at the Pi end currently. I'm also looking a 3rd time for cold joints. Will report back as time allows.

On April 22, 2022 2:11:36 PM CDT, xmodpt ***@***.***> wrote:
>What i would try in your case is unplug the pi fro the usb and power. try printing with a normal USB Pen drive if no issues, 2th step would be change the usb cable from pi's data port to front of printer for a new one with the pads correctli taped as per reference.
>
>CrAzY RaBbIt
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rudetrooper/Octoprint-Chituboard/issues/18#issuecomment-1106786537
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xmodpt** [comment]
one VERY DUM question... what type of power are you using? it is knowed that the PI is very "Special" in regards to power

**Comment by mcdviii** [comment]
I'm using an adjustable DC/DC buck converter, pulling from the line-in controller board input terminals. It's set to 5v.

On April 22, 2022 6:44:12 PM CDT, xmodpt ***@***.***> wrote:
>one VERY DUM question... what type of power are you using? it is knowed that the PI is very "Special" in regards to power
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rudetrooper/Octoprint-Chituboard/issues/18#issuecomment-1107047626
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mcdviii** [comment]
I finally had time to approach this issue again.

I've confirmed it isn't a data wiring issue by using the tape method on a data USB cable I had laying around. My custom USB cable provides the same results.

I may try to find a shielded cable to see if that improves print stalls.

I'm still leaning toward the original issue being a misconfiguration or firmware bug.

**Comment by mnbf9rca** [comment]
i'm also seeing this problem. i'm confident the wiring is fine. Printing from direct USB works fine.

**Comment by mcdviii** [comment]
Upon closer inspection, I'm running firmware very. 4.4.3. I was mistakenly reading what I think is the Chituboard version as the firmware version. Mariner software has documented issues with 4.4.3. I will downgrade to older firmware from the Elegoo firmware page for Mars 2 Pro & report back with results.

On September 13, 2022 3:41:51 PM CDT, Rob Aleck ***@***.***> wrote:
>i'm also seeing this problem. i'm confident the wiring is fine. Printing from direct USB works fine.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rudetrooper/Octoprint-Chituboard/issues/18#issuecomment-1245933968
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mcdviii** [comment]
I've downgraded my printer firmware for my Mars 2 Pro from V4.4.3-F9.23 to V4.3.13-F2.23 (using the installation steps outlined on the official firmware page.

The results are that I am able to print from the Octoprint dashboard web interface, as expected (albeit, with a delay/lag). The original issue is solved.

For more info on why 4.4.3 is problematic, see:

https://github.com/luizribeiro/mariner/issues/453

Thanks for everyone's time.

**Comment by mnbf9rca** [comment]
Unfortunately there’s no earlier version for the Jupiter :(

**Comment by mcdviii** [comment]
> Unfortunately there’s no earlier version for the Jupiter :(

Consider using the Mariner fork referenced in the issue I linked to above:

https://github.com/BlueFinBima/mariner/releases/tag/v0.2.0-1

Keep in mind--the fork is abandonware & not officially supported by any project. It may be that hack works for you.

**Comment by mnbf9rca** [comment]
Thanks for the pointer. i had to do some work to update it and repackage it so it would install, which i've now done and the package is available at https://github.com/mnbf9rca/mariner/releases/tag/0.2.0-2
