### ISSUE TITLE
using a single pi for Mars and Ender

### ISSUE THREAD

**Issue by tusharpc** [rudetrooper/Octoprint-Chituboard#22]
hi, a question, I have both the Mars Pro 2 and an Ender 3 pro side by side. I'm currently using octoprint successfully on the ender via a pi Z2W. can i run both? aka have both printers connected to usb hub that is connected to the pi. if you install the chitu plugin, the controls for the FDM printer are lost, is there any way to revert that or disable to plugin to just run the ender 3pro or vice versa ?. the whole point is to use a single pi z2w, given the shortage.

by the way, this is fantastic work !

**Comment by rudetrooper** [comment]
Its not recommended to use a single pi to control an FDM and resin printer. This application is emulating a flash drive using the microSD and the USB OTG port so adding extra traffic that could interfere with the CPU emulating the flash device could cause significant problems or print failures.

**Comment by tusharpc** [comment]
Thanks, that make sense, my question was really about using one or another not both simultaneously.
So once I install your plugin, is there a way to temporarily disable it's functionality so I can now use the octoprint default ui for ender 3

**Comment by rudetrooper** [comment]
You can disable the plugin via the Octoprint plugin manager in the settings menu. That has always been possible.
