### ISSUE TITLE
Suddenly not connecting via serial, also the serial port stays open after failure.

### ISSUE THREAD

**Issue by MythikWolf** [rudetrooper/Octoprint-Chituboard#26]
This was working.  Suddenly not working.

Changing monitoring state from "Offline" to "Opening serial connection"
Connecting to port /dev/ttyS0, baudrate 115200
Changing monitoring state from "Opening serial connection" to "Connecting"
Connected to: Serial<id=0xac54abf0, open=True>(port='/dev/ttyS0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Send: M4002
No answer from the printer within the connection timeout, trying another hello
Send: M4002
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor
Changing monitoring state from "Offline" to "Opening serial connection"
Connecting to port /dev/ttyS0, baudrate 115200
Changing monitoring state from "Opening serial connection" to "Error"
Changing monitoring state from "Error" to "Offline after error"
Unexpected error while connecting to serial port /dev/ttyS0, baudrate 115200 from hook default: error: '(22, 'Invalid argument')' @ comm.py:_open_serial:3836

Seems it stays stuck afterwards.  Working with an original Anycubic Photon.  As mentioned it was working fine.  None of the connections look like they got knocked loose.

**Comment by MythikWolf** [comment]
Nvm.  It was just a dying Pi.  I'll give it a good burial.

**Comment by MythikWolf** [comment]
Nvm. It was just a dying Pi. I'll give it a good burial.

**Comment by rudetrooper** [comment]
RIP Pi

**Comment by rudetrooper** [comment]
Also It might just be the microSD card that died not the Pi.

**Comment by MythikWolf** [comment]
Actually transferred it to a new Pi. Works fine. RIP Pi.
