### ISSUE TITLE
Photon M3 Support?

### ISSUE THREAD

**Issue by BzowK** [rudetrooper/Octoprint-Chituboard#37]
Hey Guys - 

Just curious if there's Photon M3 support.  Was going to test so disassembled it this evening, but pins aren't labeled like they are on other boards so not sure how to proceed as obviously don't want to break printer.  Below is a pic of the motherboard.  Headers which were populated / connected are highlighted in red.  The bottom of the board had no silkscreen.  Only other info I could find (more pics) [is here](https://www.anycubic.com/products/motherboard-for-photon-m3).  Any thoughts?  Thanks!

![PhotonM3MB](https://user-images.githubusercontent.com/4173211/220530411-0e84de41-b988-4179-8066-5a8943b80c68.jpg)
![PhotonM3MB2](https://user-images.githubusercontent.com/4173211/220530663-ebefacfd-6bc0-4516-8274-440fefbf449c.jpg)

**Comment by rudetrooper** [comment]
Unfortunately it doesn't support it, I don't know what instructions the anycubic printers take via the UART. I just know it's not gcode like the Chitu based printers.

**Comment by BzowK** [comment]
Disappointing - Thanks

**Comment by TheFloydman** [comment]
This is disappointing to find after I've already done all the setup for my Photon M3 Max. The board has Rx and Tx pins labeled. Is there anything I could do to help in this situation? If possible, I'd request that a note be added to supported printers that Photon M3 is _not_ supported. Including Photon in that list and stating that Anycubic boards are supported gives the impression that M3 is supported. (Not a criticism. Just a helpful edit for others who come after and don't search closed issues.)
