### ISSUE TITLE
Install script defaults to the pi user which may not exist

### ISSUE THREAD

**Issue by protoz** [rudetrooper/Octoprint-Chituboard#44]
Last year, the Raspberry Pi Foundation no longer ships with the default user `pi` this has caused my pi to fail to boot after restarting when it fails to mount the disk that does not exist.

It would be nice to have a prompt to ask which user to install with and default to pi if the user does not input anything.  The first reboot with the password change should only happen if you actually change the password.  I end up commenting out that first block because it's not very useful.

I can open a branch to make these changes if that helps

**Comment by rudetrooper** [comment]
Opening a branch would be helpful

**Comment by protoz** [comment]
Added a PR: #[46](https://github.com/rudetrooper/Octoprint-Chituboard/pull/46)

**Comment by rudetrooper** [comment]
It looks good, PR accepted
