### ISSUE TITLE
install hiccups

### ISSUE THREAD

**Issue by jd1701d** [rudetrooper/Octoprint-Chituboard#9]
When I install this it won't resume install automatically after reboot. I can get it to finish the install where it left off if I just tell it to reinstall.

**Comment by rudetrooper** [comment]
The Chituboard.sh script is supposed to be run twice. It creates a flag file to check if its resuming from reboot when you run the script the 2nd time.

**Comment by jd1701d** [comment]
That's what I started thinking, just didn't see where it was supposed to do it.
thanks for the reply, sorry it took so long for me to respond I'm just not on GitHub all that much.
